MODEL:
  ALGORITHM: "sg_imp"
  RELATION_ON: True
  USE_FREQ_PRIOR: False
  USE_RELPN: True
  BACKBONE:
    CONV_BODY: "R-101-C4"
    FREEZE_PARAMETER: True
  RPN:
    FREEZE_PARAMETER: True
  ROI_BOX_HEAD:
    NUM_CLASSES: 151
    FREEZE_PARAMETER: True
  ROI_RELATION_HEAD:
    NUM_CLASSES: 51
    FILTER_NON_OVERLAP: False
    IMP_FEATURE_UPDATE_STEP: 2
    MSDN_FEATURE_UPDATE_STEP: 2
    GRCNN_FEATURE_UPDATE_STEP: 2
    GRCNN_SCORE_UPDATE_STEP: 2